FROM python:3.7

# Setting up Docker environment
WORKDIR /code

ENV FLASK_APP=app
ENV FLASK_RUN_PORT=5000
ENV FLASK_RUN_HOST=0.0.0.0

# Copy requirements file from current directory to file in 
# containers 'code' director
COPY requirements.txt requirements.txt

# Run and install all required modules in container
RUN pip3 install -r requirements.txt
RUN pip3 install torch==1.5.1+cpu torchvision==0.6.1+cpu -f https://download.pytorch.org/whl/torch_stable.html

# Copy current directory files to containers code directory
COPY . .

# RUN app.
CMD ["flask", "run"]